spring:
 application:
 name: config-default
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  server:
       waitTimeInMsSyncEmpty: 0
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
       
       
       
