spring:
 application:
 name: local
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


  instance:
       hostname: localhost
  server:
       waitTimeInMsSyncEmpty: 0
       
       
