spring:
 application:
 name: local
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


  instance:
       hostname: localhost
  server:
       waitTimeInMsSyncEmpty: 0
       
       
